### ISSUE TITLE
Strange Error When Opening Map12

### ISSUE THREAD

**Issue by ThePlayerRolo** [Sage-of-Mirrors/Booldozer#10]
I found a strange error that states that "Your_Mod_Directory\files\Iwamoto\map12/h_02.bin" (Your_Mod_Direcotry represents your mod directory) is not found even though it is there (I checked) . However as you can see the last slash is backwards in the "missing directory".  COuld that be the root of the problem?

**Comment by Astral-C** [comment]
Fixed

**Comment by ThePlayerRolo** [comment]
> Fixed

actually no, even with the newest version, the same error shows up

**Comment by ThePlayerRolo** [comment]
This is now fixed!
