### ISSUE TITLE
Playtest doesn't work.

### ISSUE THREAD

**Issue by ThePlayerRolo** [Sage-of-Mirrors/Booldozer#11]
I click the playtest button but it just doesn't do anything, even on adminstrator mode. It seems the code of it has been commented out. Is there a reason why?

**Comment by Astral-C** [comment]
It was an idea from a wind waker editor @Sage-of-Mirrors worked on and it was decided to not implement it because the idea just wasn't going to work out, good reminder to remove that though.

**Comment by Astral-C** [comment]
Leaving this closed, decided to at least allow the playtest button to launch the game with the current selected root - doesn't launch into edited map however just starts the game as a convenience feature.

**Comment by ThePlayerRolo** [comment]
> Leaving this closed, decided to at least allow the playtest button to launch the game with the current selected root - doesn't launch into edited map however just starts the game as a convenience feature.

actually it does load into the modified game, if I edit the map .szp's  to have more ghost on a specific wave in the files folder and load the main.dol, it should be different. A similar thing is done in Mario Kart Wii Modding, that is why I know this.

**Comment by Astral-C** [comment]
No I mean the original intent of this feature was to boot the game directly into the map, so once you selected a file you'd enter into the map you had open in booldozer, this was cut in favor of just having it launch the modified root.

**Comment by ThePlayerRolo** [comment]
ah ok makes sense
