### ISSUE TITLE
Editing The Palor makes luigi in the Foyer slippery, can't go up the right stair case, and cold for some reason.

### ISSUE THREAD

**Issue by ThePlayerRolo** [Sage-of-Mirrors/Booldozer#12]
I tried to add a new ghost in the palor, however for some reason it makes luigi weird in the foyer as stated above.

**Comment by Astral-C** [comment]
Should be fixed now, you'll need a clean map2.szp (rip a new one with dolphin) since the issue was that polygoninfo/soundpolygoninfo were being written by the entity writer when that is supposed to be handled exclusively by  the collision subsystem.

**Comment by ThePlayerRolo** [comment]
ah thats intresting, so the game uses polygons for sound info?

**Comment by Astral-C** [comment]
Two separate files, soundinfo and soundpolygoninfo, one sets per polygon settings one sets the sound settings per polygon.
