### ISSUE TITLE
changing tranformation type no longer works

### ISSUE THREAD

**Issue by Zexlo** [Sage-of-Mirrors/Booldozer#15]
In the latest builds of booldozer pressing either 1, 2 or 3 no longer changes the transformation type, all objects are stuck in the scale transformation mode with manual co-ordinate editing being required to move them around the map. Maps are stuck in the translation mode similarly.
![image](https://github.com/user-attachments/assets/d9c3a068-f4d9-4cb6-901e-86ec9800d8a5)

**Comment by Astral-C** [comment]
The keybinds were changed to T,R,S after fixing text input focus

**Comment by Zexlo** [comment]
Alright! thanks for clarifying, if you haven't already remember to update the controls menu to reflect this change :)
