### ISSUE TITLE
the program keeps giving me errors when i try to open

### ISSUE THREAD

**Issue by luigitime2** [Sage-of-Mirrors/Booldozer#3]
whenever i try opening the program i get this error and originally it said i was missing dlls i added them then i got this error so idk what to do i assumed i was on a 32 bit but im running 64 bit so idk whats going on
![image](https://user-images.githubusercontent.com/76445948/228590901-a39dc022-f2ac-4c08-8a9f-902d172f375c.png)

**Comment by Astral-C** [comment]
What dll's did it say it was missing? Grabbing them from random websites could be part of what's causing this issue.

**Comment by luigitime2** [comment]
here i have them right here also this is where i grabbed them from https://www.dll-files.com
![image](https://user-images.githubusercontent.com/76445948/228602431-41cd0cfb-fbb2-455d-bba4-02a6194a6df7.png)
![image](https://user-images.githubusercontent.com/76445948/228602492-03c4c807-cb3e-4039-9cd9-a6efe987e310.png)
![image](https://user-images.githubusercontent.com/76445948/228602554-eca2627d-168f-4458-9ac5-bfc70305a9b6.png)
![image](https://user-images.githubusercontent.com/76445948/228602612-7bb8eda5-be59-495e-b7d8-bb4ad8c3e864.png)

**Comment by Astral-C** [comment]
Don't download DLLs from random websites and expect them to work, [here](https://visualstudio.microsoft.com/downloads/#microsoft-visual-c-redistributable-for-visual-studio-2022) you can grab the Visual C++ Redistributable Packages, should cover all the missing libraries. Do not continue to use the ones you downloaded.

The last one is from the Windows SDK which you can get [here](https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/).

You may need to use one of the older SDK versions from the archive provided, but please try to troubleshoot yourself first before asking here.

**Comment by luigitime2** [comment]
i tried downloading from the links you send but that didnt do anything im getting the same errors
