### ISSUE TITLE
Readme Build Clarification

### ISSUE THREAD

**Issue by zingleman** [Sage-of-Mirrors/Booldozer#4]
After attempting (and failing) to acquire the appropriate ICU libraries for a CMake build, I think the Readme could contain a small section on how to build the Booldozer binary

**Comment by Astral-C** [comment]
Was it just cmake that failed for you and where were you looking for the libraries before? Just want to make sure readme is updated properly.

**Comment by Astral-C** [comment]
readme was updated and vcpkg was added to remedy dependency issues
