### ISSUE TITLE
Launch Error Game Files

### ISSUE THREAD

**Issue by austinpilz** [Sage-of-Mirrors/Booldozer#6]
On Windows 11, I've successfully built Booldozer in Visual Studio Code.

When I attempt to open `booldozer.exe`, the main window appears for a moment and then closes.

The terminal window behind it reads:

```
Unable to load game archive files\Game\game_usa.szp
Compiling shaders for bin?
```

I'm unable to locate a directory to place the game files? What's the best way to rectify this?

**Comment by Astral-C** [comment]
This is a bug due to a game root not being set, needs to be fixed.

**Comment by austinpilz** [comment]
Do I need to be setting the root myself in code, or is this a bug at the project level?

**Comment by Astral-C** [comment]
Project level, pushed a commit this morning that should fix it.

**Comment by Astral-C** [comment]
Closing this for now, should be fixed, let me know if it still crashes.
