### ISSUE TITLE
Selecting a room crashes the application?

### ISSUE THREAD

**Issue by ThePlayerRolo** [Sage-of-Mirrors/Booldozer#9]
Everytime I select a .szp or .arc with a name relating to the map, the program just crashes. Is there a specific folder containting the correct .arcs/.szps? I am new here so I don't really know what directorys are for what, and it doesn't help some of the folders are presumably named after the devs that worked on them.

**Comment by Astral-C** [comment]
Run with powershell or cmd and post logs and booldozer settings please.

**Comment by ThePlayerRolo** [comment]
The log of command prompt when opening it just says "Freeing Archive". My sha is 0699f1c279ea4a505d3f7cdfb73d79c07e153d02da8571b7bc5f500349c32499 and my settings are {"dolphin_path":"C:\\Users\\Personal\\Downloads\\dolphin-2409-x64\\Dolphin-x64\\Dolphin.exe","is_dol_patched":true,"last_opened_map":"C:\\Users\\Personal\\Documents\\Luigis Mansion\\Test\\files\\Iwamoto\\map0\\map0.arc","last_saved_directory":".","root_path":"C:\\Users\\Personal\\Documents\\Luigis Mansion\\Test"}      All mentions are Personal are my irl name just censored for obvious reasons. I set the root path of the luigs mansion file to the folder that contains the files and sys folder.

**Comment by Astral-C** [comment]
Open `files/Map/mapX.szp`, try map2 first. Is Freeing Archive the only thing in the logs? There should be more.

**Comment by ThePlayerRolo** [comment]
How do you create a log? Sorry but I thought by log you meant what the cmd prompt booldozer created said.  Also btw, selecting one of those also crashes the application.

**Comment by Astral-C** [comment]
Run booldozer from a command prompt or from powershell, it should be printing out a lot more in, those are the logs. Post the entire log.

**Comment by ThePlayerRolo** [comment]
It Quite Literally just says  this before crashing: [DOL]: SHA256 of executable is 0699f1c279ea4a505d3f7cdfb73d79c07e153d02da8571b7bc5f500349c32499 Freeing Archive

**Comment by Astral-C** [comment]
Hm, that should be `Freeing Archive data` so I'm guessing its having some sort of issue loading archives. Will take a look.

**Comment by ThePlayerRolo** [comment]
Heres the log after the first log update. 
[Log.txt](https://github.com/user-attachments/files/17636368/Log.txt)
The strange thing is that even after the "even more logging" commit update, it still has the same exact log.

**Comment by ThePlayerRolo** [comment]
![image](https://github.com/user-attachments/assets/0270ac00-ad92-4eb4-bbeb-e4272a81543c)
Are they gonna kiss 💀 
Anyways it works! Thanks!
